aws-cloudformation/cloudformation-cli-python-plugin

README.md

Add installation instructions (fixes #48)

---

.gitignore
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
tests/lib/metrics_test.py

#22 
Adds an initial metrics publisher

feat: add initial metric publisher

---

src/cloudformation_cli_python_lib/scheduler.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/scheduler_test.py
tests/lib/utils_test.py

*Issue #, if available:* #57
Implements scheduler class copying the behavior of the java implementation pretty closely.
Still need to be wired up, in the service of keeping the code review manageable, will leave that for a follow up pr.

implement CloudWatchScheduler class

---

python/rpdk/python/codegen.py
python/rpdk/python/templates/handlers.py
src/cloudformation_cli_python_lib/resource.py
tests/lib/resource_test.py

*Issue #, if available:* #54 , #22 
*Description of changes:* Store the type name. Useful for resource authors, but also for us to derive the correct metric namespace.

Provide type name

---

tests/lib/resource_test.py

*Issue #, if available:* N/A
*Description of changes:* Both PRs built by themselves... still better than having to manually rebase 😛 

Merge failure between #64 and #65

---

.travis.yml
README.md
python/rpdk/python/codegen.py
tests/lib/resource_test.py
tests/lib/scheduler_test.py
tests/lib/utils_test.py

*Issue #, if available:* N/A
*Description of changes:* Use a CI runner that doesn't require logging in.

Public CI runs

---

README.md

* Title is required to be between 20-250 characters. The old value was only 3 and would fail validation.
* TestCode is required according to the generated example template.

updated example test input

---

python/rpdk/python/__init__.py

version bump -> 2.0

---

python/rpdk/python/templates/requirements.txt
setup.py
src/setup.py

dependencies bump, dev status change

---

README.md
package_lib.sh

*Description of changes:* Update ReadME to use public released plugin.

Update README to use public released plugin

---

.travis.yml
python/rpdk/python/__init__.py
python/rpdk/python/templates/requirements.txt
setup.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
src/setup.py
tests/plugin/codegen_test.py

*Issue #, if available:* fixes #113, fixes #73
adding previous stack tags and allowing docker 3.7<= && <= 4.3.1

Previous tags and allowing newer Docker versions

---

setup.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
src/setup.py
tests/lib/log_delivery_test.py
tests/lib/resource_test.py

adding previous system tags

---

setup.py

*Description of changes:* Loosening requirements to make this plugin compatible with new releases.

Loosening requirements for cloudformation-cli

---

src/setup.py

*Description of changes:* Bumping version for release

Bump version for release

---

src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/resource.py
tests/lib/resource_test.py

Removed Exception msg from InternalFailure

---

.pylintrc
setup.py
src/cloudformation_cli_python_lib/interface.py

introduced in https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/137/commits/210e80ba797f5bee5b40020885d0e44154ad230b by @jotompki
fixes https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/security/dependabot

removing explicit urllib3 pinning

---

python/rpdk/python/__init__.py

especially to release https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/155

cloudformation-cli-python-plugin version 2.1.3

---

python/rpdk/python/codegen.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py

#162 merging external contribution with some small changes. 
Passed local testing with sample resource. 
local build:
```
$ pre-commit run --all-files
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...................................................................Passed
Pretty format …
```

Added Type[BaseModel] Annotation to TypeConfiguration

---

src/setup.py

Lib Version Bump

---

src/setup.py

Simple version bump before tagging next release.

Bump lib version to 2.1.10

---

src/setup.py

Simple version bump before tagging a new release
---

Bump lib version to 2.1.11

---

src/setup.py

Bump lib version to 2.1.12

---

.pre-commit-config.yaml

- Pin `importlib-metadata<5` until https://github.com/PyCQA/bandit/issues/956 is resolved 

fix(test) - Pin importlib to make bandit work

---

.gitattributes
.github/workflows/pr-ci.yml

- Updated github actions to the latest versions.  
- Added caching for pip and pre-commit
- Added Python 3.9 to CI testing
- Added Windows and MacOS to CI Testing
Windows errors will resolve with #208 

Chore(CI):  update github actions to latest versions, python 3.9, and multi-os

---

python/rpdk/python/codegen.py

*Issue #93 
Logging into console, when pip build is finished.

Logging when pip build is finished.

---

.github/workflows/pr-ci.yml

Closes #222 
remove unnecessary branch merging checks.

chore(CI): remove unneeded github workflows

---

python/rpdk/python/__init__.py
src/setup.py

Incrementing a version for both plugin and library (v2.1.7 and v2.1.14)

version bump

---

python/rpdk/python/__init__.py

reverting version bump for plugin

Revert plugin version bump

---

python/rpdk/python/__init__.py
src/setup.py

bump version

---

tests/lib/hook_test.py
tests/lib/resource_test.py

- Patch more boto sessions for certain scenarios

fix(test) - Patch more boto sessions for certain scenarios

---

python/rpdk/python/__init__.py
src/setup.py

bump version to 2.1.16

---

src/setup.py

Bumping python lib version to 2.1.17

bump python lib version to 2.1.17

---

python/rpdk/python/__init__.py
src/setup.py

PR to to bump package version. 

bump version to 2.1.18
