src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/resource_test.py

*Issue #, if available:* #57
doesn't include [reportProgress](https://github.com/aws-cloudformation/aws-cloudformation-rpdk-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/CloudFormationCallbackAdapter.java#L51-L83) which will come in a future pr.

enable local and cloudwatch handler re-invocation while IN_PROGRESS

---

src/cloudformation_cli_python_lib/callback.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/scheduler.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/callback_test.py
tests/lib/interface_test.py
tests/lib/log_delivery_test.py
tests/lib/resource_test.py
tests/lib/scheduler_test.py

*Issue #, if available:* Also fixed #60 
completes support for async handlers. I've end-to-end tested async CREATE using both local and cloudwatch reinvocations.
I optimised for getting this pr in as quickly as possible, over making the code pristine. This gets the plugin fully functional and can iterate/improve from here as we go.
Also fixes a few small bug that were exposed during testing:
* properly serialize `ProgressEvent` responses (was getting `Internal Failure` errors)
* log_delivery was creating duplicate handlers (duplicate messages delivered) when lambda re-used a container
* cloudwatch rules/targets were not being cleaned up

Report progress

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

*Issue #, if available:* #56 
*Description of changes:* See issue. Error message is now:
```
$ cfn submit --dry-run
Starting Docker build. This may take several minutes if the image 'lambci/lambda:build-python3.7' needs to be pulled first.
=== Caught downstream error ===
Could not connect to docker - is it running?
---
If debugging indicates this is a possible error with this program,
please report the issue to the team and include the log file 'rpdk.log'.
Issue tracker: https://github.com/aws-cloudformation/aws-cloudformation-rpdk/issues
```

Catch ConnectionError when Docker isn't running

---

src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
tests/lib/metrics_test.py
tests/lib/resource_test.py

*Issue #, if available:* Fixes #22 
Wires up metrics to publish to cwl in platfom acc and provider acc (if configured). 
refactored `metrics.py` to handler multiple boto3 clients per publishing event and address a few gaps with the java plugin. 
Tested end to end, metrics showing up as expected in provider account.
`Resource.__call__` is becoming unwieldy, could use a refactor, but didn't want to muddy this pr with more refactors, so will address in a future pr.

implement CloudWatch metrics

---

.pre-commit-config.yaml
setup.cfg
src/cloudformation_cli_python_lib/callback.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/scheduler.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/interface_test.py
tests/lib/log_delivery_test.py
tests/lib/metrics_test.py
tests/lib/resource_test.py
tests/lib/scheduler_test.py
tests/lib/utils_test.py

*Issue #, if available:* N/A
*Description of changes:* The main change is to use `SessionProxy`, instead of passing credentials around (although they are still needed for the re-invoke). I've also changed the way the request is parsed, first we try and parse the platform part. If this fails, it's now an `InternalFailure`. Then, the `ProviderLogHandler` uses this parsed data instead of re-parsing the event data itself. Finally, the request is "parsed" and if this fails, it is an `InvalidRequest` for now ("parsed" but not really, see #27 ). Both of these steps will make adding a validation library much easier.
I also reworked the MetricPublisher interface a bit like we discussed in #69 .
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

Always use SessionProxy

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/78
Explicitly tell Docker Run to run commands as the current user. Without this change, `pip install ... -t ./build/` will run as `root` which means `root` owns the `./build/` folder and the subsequent CLI actions fail due to a permissions mismatch.

fixed docker folder permission issue

---

.pylintrc
.travis.yml
python/rpdk/python/codegen.py
python/rpdk/python/resolver.py
python/rpdk/python/templates/models.py
src/cloudformation_cli_python_lib/callback.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/recast.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/callback_test.py
tests/lib/interface_test.py
tests/lib/recast_test.py
tests/lib/resource_test.py
tests/lib/sample_model.py
tests/lib/utils_test.py
tests/plugin/resolver_test.py

improves the deserialization of the raw model into type-hinted python objects.
* ser/de can now handle complex schemas containing arrays and objects
* CloudFormation service is casting all primitive types (`integer`, `number`, `boolean`) into strings. This provides a hacky, but easy-to-remove-once-fixed-upstream, convertor that introspects the type hints and re-casts them back to their intended types.
This looks pretty large on the surface, but line count is predominantly test case data in `tests/lib/recast_test.py` and `tests/lib/sample_model.py`.

Improve model deserialization

---

src/cloudformation_cli_python_lib/utils.py
tests/lib/utils_test.py

*Issue #, if available:* Fixes #83
On re-invocations the serialization logic strips empty keys from the json, so `{"systemTags": {}}` becomes "{}". This PR makes the systemTags key optional.

systemTags are sometimes ommitted in the request

---

python/rpdk/python/data/Python.gitignore

Credentials committed in `sam-tests/` in several `resource-providers` already:
[gamelift](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-gamelift/pull/9#discussion_r432213015)
[cloudwatch](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudwatch/pull/2/files/1afad8dd9d53ae5210c0624ee2a8ead7818993ae#diff-83d85f3c2f1785dcc53ab51e9abd2f2c)
Other language plugins as well:
[Java](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/271)
[Go](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/pull/144)

add sam-tests/ to initially generated default .gitignore

---

python/rpdk/python/templates/models.py

Added resolved type reference. used example from #96 
result:
```python
@dataclass
class ResourceModel(BaseModel):
InstanceId: Optional[str]
Cloud9InstancePolicy: Optional["_Cloud9InstancePolicy"]
@classmethod
def _deserialize(
cls: Type["_ResourceModel"],
json_data: Optional[Mapping[str, Any]],
) -> Optional["_ResourceModel"]:
if not json_data:
return None
dataclasses = {n: o for n, o in getmembers(sys.modules[__name__]) if isclass(o)}
recast_object(cls, json_data, dataclasses)
return cls(
InstanceId=json_data.get("InstanceId"),
Cloud9InstancePolicy=Cloud9InstancePolicy._deserialize(json_data.get("Cloud9InstancePolicy")),
)
_ResourceModel = ResourceModel
@dataclass
class Cloud9InstancePolicy(BaseModel):
PolicyName: Optional[str] …
```

fixed resource reference

---

src/cloudformation_cli_python_lib/recast.py
tests/lib/recast_test.py

*Issue #, if available:* Fixes #90 
`recast.py` currently expects all primitives to be strings, which is the case for initial invocations, but re-invocations from cloudwatch events are passing in already recast events. This fix should handle that.

recasting might happen on already cast objects (re-invokes)

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

This one will remove to use local file for python-lib but use the published cloudformation-cli-python-lib from PyPI. 
Verified in unicorn-maker Python plugin. 

Use cloudformation-cli-python-lib from PyPi

---

setup.py

*Description of changes:* Need the right description type to publish.
__Before__
```
twine upload --repository-url https://test.pypi.org/legacy/ dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: aws-cloudformation-developers
Enter your password:
Uploading cloudformation_cli_python_plugin-2.0.0-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23.3k/23.3k [00:01<00:00, 21.5kB/s]NOTE: Try --verbose to see response content.
HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText. See https://test.pypi.org/help/#description-content-type for more information. for url: https://test.pypi.org/legacy/
``` …

Update the description content type to markdown

---

src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/utils_test.py

additional properties to `BaseResourceHandlerRequest` interface:
*- there are no good methods in `boto.session` or `regions` to retrieve current partition. we can use [get_available_partitions](https://github.com/boto/botocore/blob/develop/botocore/regions.py#L98) to get list of partitions but that is not what is needed. We cant get endpoint interface either as [get_available_endpoints](https://github.com/boto/botocore/blob/develop/botocore/regions.py#L104) returns list of `str`. There is an outstanding PR to get partition by region https://github.com/boto/botocore/pull/1715. We could replicate something like that but might make sense to just wait.
By submitting this pull request, I confirm that my contribution is made under the terms of …

added new properties

---

src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
tests/lib/metrics_test.py

Main PR for Java plugin: https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/293
The removed account ID is the customer account ID instead of the provider account ID. This means that for public types, a new metric namespace would be created each time we need to emit metrics. The main issue with this is that the internal and logging failure alarms will not work properly and service teams may not be notified of issues.

Removed account ID from metric namespace

---

python/rpdk/python/data/Python.gitignore

[Java](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/682214d782e20ee197ae2711bde06602d12a5d20/python/rpdk/java/data/java.gitignore#L20) and [Go](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/blob/7b9fc8d8848ad2666298fbcf077c0f2d4d264a2b/python/rpdk/go/data/go.gitignore#L6) plugins already have this in `.gitignore`
`sam-tests/` `.gitignore` PRs:
[Java](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/pull/271)
[Python](https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/97)
[Go](https://github.com/aws-cloudformation/cloudformation-cli-go-plugin/pull/144)

add rpdk.log to initially generated default .gitignore

---

setup.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/log_delivery_test.py
tests/lib/metrics_test.py
tests/lib/resource_test.py
tests/lib/utils_test.py

*Issue #, if available:* #112 #109 
*Description of changes:* This change makes some request fields optional/removes certain fields so that contract testing via `cfn test` can complete successfully without library errors. Below are a list of the changes to the request:
* Made `resourceType`, `resourceTypeVersion`, and `stackId` optional. Making `resourceType` optional led to some issues with metrics publishing, so I had to refactor the MetricPublisher and MetricsPublisherProxy. This led to the layout being much more in line with the java plugin, where the proxy [has no required arugments for construction and simply loops through available publishers when publishing](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation …

Make certain request fields optional to unblock contract testing.

---

src/cloudformation_cli_python_lib/utils.py
src/setup.py

*Issue #, if available:* #122 
*Description of changes:* While working on #120, went from completely removing responseEndpoint on the first iteration to adding it back in the next time around. Ideally, this should be marked as optional, as it is still sent from CloudFormation's backend. This should work with both `cfn test` and stack provisioning. Will fully test out in the morning before releasing.

Make responseEndpoint optional

---

python/rpdk/python/codegen.py
python/rpdk/python/parser.py
setup.py
tests/plugin/parser_test.py

Add ability to consume the use docker flag from the `cloudformation-cli`.

Receive use_docker flag from the cli

---

src/cloudformation_cli_python_lib/recast.py
tests/lib/recast_test.py
tests/lib/sample_model.py

Handle the case when the values of a dict type are predetermined in the schema, and are a primitive type.
For instance a property definition like this:
```json
"APrimitiveTypeDict": {
"type": "object",
"patternProperties": {
".*": {
"type": "boolean"
}
}
}
```
This generates an attribute like I added in the test: `Optional[MutableMapping[str, bool]]`
Without this fix, the following exception gets raised: 
```
Traceback (most recent call last):
File "/var/task/cloudformation_cli_python_lib/resource.py", line 104, in _parse_test_request
).to_modelled(self._model_cls)
File "/var/task/cloudformation_cli_python_lib/utils.py", line 127, in to_modelled
desiredResourceState=model_cls._deserialize(self.desiredResourceState),
File …
```

Fix recast_object for dict values of primitive type

---

python/rpdk/python/templates/handlers.py

Updates the handlers.py template file to be more in line with the contract definitions - https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html
* This PR adds the call to `read_handler` at the end of create and update, instead of returning a success progress event. 
My understanding is that this is required for stabilization and also ensures the model contains any readOnly attributes
* It also sets the model to None when returning a progress event in the delete handler. 
> When the delete handler returns SUCCESS, the ProgressEvent object MUST NOT contain a model.

Call read handler on create/update and return empty model on delete

---

.travis.yml
before_deploy.sh
python/rpdk/python/__init__.py
python/rpdk/python/templates/requirements.txt
src/setup.py

*Description of changes:* This change add a travis deployment job for both the plugin and support library. Basically, depending on the tag naming, we will release the plugin or lib. If a tag contains "plugin", the before_deploy script will not change the directory, and travis will release what is in the root directory. If a tag contains "lib", the directory changes to "src" and the support library is released. (Thanks to @lukewrites for detailing this solution for multiple pypi packages in one repo in their repo here: https://github.com/lukewrites/silly-package)
Tested on my local fork with the test pypi repository.
This also contains a version bump for both plugin and lib packages so that once merged, we can tag this commit and release it.
Example jobs: 
* [lib …

Add travis release for both plugin and support lib.

---

src/cloudformation_cli_python_lib/utils.py
tests/lib/utils_test.py

prevents deserialization exceptions on any undesired properties
```terminal
% pre-commit run --all-files
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...................................................................Passed
Pretty format JSON...................................(no files to check)Skipped …
```

non-strict deserializer for request data

---

setup.py

`docker` is already an indirect dependency from `cloudformation-cli`, so this was just pinning `docker` version stricter than `cloudformation-cli`, which causes issues
https://github.com/aws-cloudformation/cloudformation-cli/issues/727

removing explicit docker pinning

---

python/rpdk/python/codegen.py
src/setup.py

copying https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/pull/144/
---
blocked on https://github.com/aws-cloudformation/cloudformation-cli/pull/762 being released

cloudformation-cli-python-lib version 2.1.6

---

python/rpdk/python/codegen.py
python/rpdk/python/templates/models.py
setup.py
src/cloudformation_cli_python_lib/exceptions.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
tests/data/schema-with-typeconfiguration.json
tests/lib/interface_test.py
tests/lib/resource_test.py
tests/lib/utils_test.py
tests/plugin/codegen_test.py

Add TypeConfiguration support for Resource Types.
-------------------------------------------------------------
*Local CI run*
`pre-commit run --all-files`:
```
isort....................................................................Passed
black....................................................................Passed
Check for case conflicts.................................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Flake8...................................................................Passed
Pretty format …
```

Adding support for TypeConfiguration

---

src/cloudformation_cli_python_lib/boto3_proxy.py
src/cloudformation_cli_python_lib/log_delivery.py
tests/lib/boto3_proxy_test.py

Allows for the user of the plugin to retrieve the boto3 Session object
and use it directly as needed.
*Issue #, if available:* #151
*Description of changes:* Add `session` object to `SessionProxy` class to allow direct use.

Add Session Object to SessionProxy

---

.pre-commit-config.yaml
python/rpdk/python/codegen.py
src/cloudformation_cli_python_lib/recast.py
tests/lib/recast_test.py
tests/plugin/codegen_test.py

Added a method to provide plugin information that is included in artifact zip.
Plugin information includes,
plugin-tool-version - The version of the cli tool
plugin-name - "java"/"python"/"go". Here it is "python"
I also updated the mypy version and made few other changes based on pre-commit run.
*Testing:*
- Unit testing
- Local testing
```
less .cfn_metadata.json 
```
```
{"plugin-tool-version": "2.1.4", "plugin-name": "python", "cli-version": "0.2.19"}
.cfn_metadata.json (END)
```

Added a method to provide plugin information that is included in artifact zip

---

.pylintrc
python/rpdk/python/__init__.py
python/rpdk/python/codegen.py
python/rpdk/python/templates/hook_handlers.py
python/rpdk/python/templates/hook_models.py
python/rpdk/python/templates/requirements.txt
python/rpdk/python/templates/target_model.py
setup.py
src/cloudformation_cli_python_lib/__init__.py
src/cloudformation_cli_python_lib/cipher.py
src/cloudformation_cli_python_lib/exceptions.py
src/cloudformation_cli_python_lib/hook.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/resource.py
src/cloudformation_cli_python_lib/utils.py
src/setup.py
tests/lib/cipher_test.py
tests/lib/hook_test.py
tests/lib/interface_test.py
tests/lib/log_delivery_test.py
tests/lib/metrics_test.py
tests/lib/resource_test.py
tests/lib/utils_test.py
tests/plugin/codegen_test.py

This release adds support for creating Hooks using the CFN CLI Python plugin
* Initialize a Hook project with `cfn init --artifact-type HOOK --type-name <type-name>`
* For example: `cfn init --artifact-type HOOK --type-name My::Test::Example`
* Using `cfn init` without parameters will now first ask if you want to create a resource,  module, or a hook. If you choose to create a hook, you will be asked to choose a language plugin. After choosing a plugin, a hook project will be generated with boilerplate code which you can use as a starting point to make your changes.
* Use `cfn validate` to validate your hook before submitting
* Use `cfn submit` to register your hook, making it available for use by CloudFormation in your AWS account
Related PRs:
* …

Add support for Hooks

---

src/cloudformation_cli_python_lib/recast.py
tests/lib/recast_test.py
tests/lib/sample_model.py

Related to #172 
When trying to recast dict items, if the key is not found, it will iterate over the "nested" dict items first.
At first, I had 
```python
except KeyError:
child_cls = _field_to_type(cls.__dataclass_fields__[k].type, k, classes)
for _child, _child_definition in v.items():
recast_object(child_cls, _child_definition, classes)
_new_child = child_cls._deserialize(_child_definition)
json_data[k][_child] = _child_definition
```
which works fine. However, then the recast_test would not pass as the type for `json_data[k][_child] ` would be that of `cls` instead of more "primitive" ones.
Drawback to that is that in the handlers code, every object is a `dict` instead of being of type `cls`. which means no access to the object attributes directly.
Welcome for suggestions on how to …

Implemented nested dict re-cast

---

src/cloudformation_cli_python_lib/cipher.py
src/cloudformation_cli_python_lib/exceptions.py
src/cloudformation_cli_python_lib/hook.py
tests/lib/cipher_test.py
tests/lib/hook_test.py

For `HOOK` types, credentials are encrypted service side before invoking the hook. Credentials are decrypted while setting up the runtime before calling the authored handler code.  
Sometimes decryption of the credentials fails when customer is missing permissions for decrypting the credentials. This usually happens when customer specifies their own hook execution role.  
To avoid this being marked as an `InternalFailure` service side, having the Hook wrapper return an `AccessDenied` error code instead back to CFN whenever decryption of credentials fails

Return AccessDenied Error Code when failing to decrypt credentials

---

.pre-commit-config.yaml

This simply updates black to fix the broken workflow (psf/black#2964).
See [successful workflow](https://github.com/darrylabbate/cloudformation-cli-python-plugin/actions/runs/2092842046) from my fork.

Update pre-commit dependency to fix GitHub Actions workflow

---

src/cloudformation_cli_python_lib/log_delivery.py

CC:
- #181
- #182
This change avoids an issue where the `logging.getLogger().handlers` list is unconditionally subscripted with index `0`, which can cause an `IndexError` to be thrown if no handlers were previously defined. By moving the `addFilter()` call after the `addHandler()` call, this at least guarantees `handlers[0]` will have been initialized first.
I've gone ahead and tested this change manually against CFN and have found no issues.
---

Move `addFilter()` call after `addHandler()`

---

src/setup.py

The `cloudformation-cli-python-lib` has a dependency on the `aws-encryption-sdk` for python. The encryption SDK itself has a [dependency on](https://github.com/aws/aws-encryption-sdk-python/blob/master/requirements.txt#L2) the python [`cryptography` library](https://cryptography.io/en/latest/). 
Have had some reports on `HOOK` type handler returning this internal error:
```
cannot import name 'int_from_bytes' from 'cryptography.utils' (/var/task/cryptography/utils.py)
```
According the [change log](https://cryptography.io/en/latest/changelog/), version 37.0.0 was recently release and includes some breaking changes.  
I have tested using the previous v36 version and the issue is fixed. <s>Adding cyrptography version less than v37 as a requirement for the CFN CLI …

fix: Upgrade aws-encryption-sdk dependency

---

python/rpdk/python/templates/hook_handlers.py

Updated the initial `guided-aws` boilerplate code to use a real world example of verifying an S3 bucket's encryption has not been changed.
Related PR:
* https://github.com/aws-cloudformation/cloudformation-cli/pull/884

Updated initial hook boilerplate code to target a real resource type

---

src/cloudformation_cli_python_lib/hook.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/resource.py
src/setup.py
tests/lib/log_delivery_test.py

*Issue #, if available:* https://github.com/aws-cloudformation/cloudformation-cli-python-plugin/issues/189
*Description of changes:* Adds optional argument to Hook to establish log formatter for handler.

Log Formatter

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

#192 
- Update the docker images used to leverage public ECR and Amazon published images https://gallery.ecr.aws/lambda/python
- Currently used images don't look to be maintained and can result in rate limiting from docker hub

Use Amazon ECR images for mimicing lambda with docker

---

.pylintrc
tests/lib/boto3_proxy_test.py
tests/lib/cipher_test.py
tests/lib/log_delivery_test.py
tests/lib/metrics_test.py

- Current versions of tests rely on some information being in `~/.aws/config` when doing mocks. This PR will completely remove that dependency. 
You will have issues with the current version of the tests if you have no `~/.aws/config` or are using the `credential_process` attribute in a profile

fix(test) - Reduce dependency on AWS config file

---

.github/workflows/pr-ci.yml
.pre-commit-config.yaml
mypy.ini
python/rpdk/python/codegen.py
python/rpdk/python/templates/handlers.py
python/rpdk/python/templates/hook_handlers.py
python/rpdk/python/templates/hook_models.py
python/rpdk/python/templates/models.py
python/rpdk/python/templates/target_model.py
setup.py
src/cloudformation_cli_python_lib/boto3_proxy.py
src/cloudformation_cli_python_lib/cipher.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/log_delivery.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/utils.py
tests/lib/cipher_test.py
tests/lib/exceptions_test.py
tests/lib/hook_test.py
tests/lib/interface_test.py
tests/lib/log_delivery_test.py
tests/lib/metrics_test.py
tests/lib/recast_test.py
tests/lib/resource_test.py
tests/lib/sample_model.py
tests/lib/utils_test.py
tests/plugin/codegen_test.py
tests/plugin/parser_test.py

Pre-commit file was using old and deprecated versions in many cases.
Updated all versions in `.pre-commit-config.yaml` and applied linting changes that were found

chore(tests): Update precommit config yaml file to newest versions

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

Closes #100 
Docker command to run container was getting the local user euid and gid. These attributes do not exist on non-UNIX-like OSes like Windows.
Put in check for the command to complete successfully but if not to default to root:root. Windows ignores these attributes and the Docker file system has built in safeguards around this.

fix(docker): During `cfn submit` docker commands were not working on Windows

---

.pre-commit-config.yaml

Reverts aws-cloudformation/cloudformation-cli-python-plugin#202
With the pre-commit updates from #206 this pin no longer looks to be necessary.

Revert "fix(test) - Pin importlib to make bandit work"

---

python/rpdk/python/codegen.py

Closes #212 
switch try/except to if path exists before build path removal

fix(log): filenotfound exception when `cfn submit` cluttering logs

---

python/rpdk/python/codegen.py

Related to issue #100 
Pip upgrade command removed.  This was causing issues on non-windows machines and was only necessary for Windows machines with cloudformation resources using Python 3.6

fix(docker): pip upgrade command removed

---

python/rpdk/python/codegen.py
src/cloudformation_cli_python_lib/resource.py
tests/plugin/codegen_test.py

Closes #210 
Paths were hardcoded with `/` which is incorrect on Windows.  Used os.path.join for OS agnostic path joins.

Fix(CI): Fix unittests on Windows

---

src/cloudformation_cli_python_lib/exceptions.py
src/cloudformation_cli_python_lib/interface.py

This PR adds a `UnsupportedTarget` error code.
Related PR: https://github.com/aws-cloudformation/cloudformation-cli/pull/945

Add UnsupportedTarget error code

---

.github/workflows/pr-ci.yml
python/rpdk/python/codegen.py
python/rpdk/python/parser.py
setup.py
tests/plugin/parser_test.py

- Add support for to create resource extensions in Python 3.8 and 3.9
- Remove support for testing on Python 3.6

chore(lifecycle) - Add support for to create resource extensions in Python 3.8 and 3.9

---

python/rpdk/python/codegen.py

Closes #228 #229 
Lambda image is missing git/ssh/svn switching to SAM python build image instead.

fix(submit): Switch to ECR SAM build python container image

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

Closes #235 
Non docker - python requirements build on Windows requires shell parameter for subprocess.run.  This causes non-docker builds on POSIX systems to not gather dependencies.  Changed to use altered statement only on windows.

fix(submit) - pip build on windows command causing unintended consequence on posix

---

src/cloudformation_cli_python_lib/resource.py

Closes #230 
If desiredResourceState or desiredResourceTags is empty then default to empty dictionary instead of None.

If desired resource state/tag is none, default to empty dictionary

---

python/rpdk/python/codegen.py
python/rpdk/python/parser.py
tests/plugin/codegen_test.py
tests/plugin/parser_test.py

Closes #227 
This is to allow for a --no-docker option from the command line.  This will also suppress the prompt asking to confirm no-docker usage.

feat(cli): no-docker option

---

python/rpdk/python/codegen.py
python/rpdk/python/templates/target_model.py
tests/plugin/codegen_test.py

Running `cfn generate` will now generate Python models for HOOK targets

Generate models for hook targets

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

- Update docker run to force platform to `linux/amd64`
On Mac OS with the M1 chips docker run will use ARM which results in python packages that have binaries pulling down the aarch based binaries.  This will force docker to use a linux/amd64 image so we get the right binaries downloaded.

udpate docker run to force platform to linux/amd64

---

src/setup.py

Closes #253 
Newest version of python cryptography breaks contract testing.  Pinning to lower version of cryptography.

Pin to lower version of cryptography

---

src/setup.py

*Issue #, if available:* #255
A previous commit pinned the version of `cryptography` to `<40.0.0` to resolve incompatibility between the version of the `aws-encryption-sdk` being used with this project and the latest `cryptography` library. However, this package has no direct dependency on `cryptography` and the `aws-encryption-sdk` fixed their compatibility issue with a patch version bump in `3.1.1`, so we should use that patch version instead of pinning to an older version of a downstream dependency.

Bump version of encryption sdk to remove cryptography pinning

---

python/rpdk/python/codegen.py
tests/plugin/codegen_test.py

Closes #211 
Use docker container.run remove option instead of auto_remove. If the job errors, this will allow the user to run the container outside the run and troubleshoot further.  This will also mean on error manual cleanup of the containers would be necessary.

switch auto_remove with remove in codegen and tests

---

.github/workflows/pr-ci.yml
.pre-commit-config.yaml
.pylintrc
python/rpdk/python/codegen.py
python/rpdk/python/parser.py
setup.py
src/cloudformation_cli_python_lib/hook.py
src/cloudformation_cli_python_lib/identifier_utils.py
src/cloudformation_cli_python_lib/interface.py
src/cloudformation_cli_python_lib/metrics.py
src/cloudformation_cli_python_lib/recast.py
src/cloudformation_cli_python_lib/resource.py
src/setup.py
tests/lib/metrics_test.py
tests/lib/utils_test.py
tests/plugin/codegen_test.py
tests/plugin/parser_test.py

- Add support for python up to 3.11

Add support for python up to 3.11

---

src/cloudformation_cli_python_lib/hook.py
src/cloudformation_cli_python_lib/resource.py

- Add noqa for BaseException for newer version of flake8

Add noqa for BaseException
